#### General Configuration
# worker_processes: Number of NGINX processes. Default = 1
worker_processes = "auto"
worker_rlimit_nofile = 8192

#### Events Context Configuration
[events]
# worker_connections: Connections per Worker Process.  Default = 1024
worker_connections = 1024


#### HTTP Context Configuration
[http]
# http.sendfile: Enable (on) or disable (off) Sendfile Support.  Default = on
sendfile = "on"

# http.tcp_nopush: Enable (on) or disable (off) use of TCP_NOPUSH or TCP_CORK socket option. Default = on
tcp_nopush = "on"

# http.tcp_nodelay: Enable (on) or disable (off) use of the TCP_NODELAY option. Default = on
tcp_nodelay = "on"

# http.keepalive_timeout: Timeout on client connection keepalive, in seconds. Default = 75
keepalive_timeout = 60

[http.listen]
  port = 80
  bind = "0.0.0.0"
  local_only = false

[mmsn]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[money-checker-server]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[wiki]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[home-whale-dis]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[hawaii-alaska-whale-dis]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[media-whale-dis]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[west-coast-whale-dis]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[pacific-northwest-whale-dis]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[west-coast-training-whale-dis]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[east-coast-training-whale-dis]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[training-whale-dis]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[money_data_server]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[acoustics-whaledisentanglement]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""
  
[requestbin]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[phpmyadmin]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""

[wildbook]
  domain_names = []
  ssl_certificate = ""
  ssl_certificate_key = ""
